import Vue from 'vue';
import {
    Button,
    Form,
    FormItem,
    Input,
    Message,
    MessageBox,
    Container,
    Aside,
    Header,
    Main,
    Menu,
    MenuItem,
    Submenu,
    Breadcrumb,
    BreadcrumbItem,
    Tooltip,
    Card,
    Row,
    Col,
    Table,
    TableColumn,
    Tag,
    Popover,
    Dialog,
    Tabs,
    TabPane,
    Carousel,
    CarouselItem,
    Pagination,
    Select,
    Option,
    DatePicker,
    Checkbox,
    CheckboxGroup,
    Collapse,
    CollapseItem,
    Switch,
    Icon,
    Upload,
    Alert,
    Radio,
    RadioGroup
} from 'element-ui';

Vue.use(Button);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Input);
Vue.use(Header);
Vue.use(Container);
Vue.use(Aside);
Vue.use(Main);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(MenuItem);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
Vue.use(Tooltip);
Vue.use(Card);
Vue.use(Row);
Vue.use(Col);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Popover);
Vue.use(Tag);
Vue.use(Dialog);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Carousel);
Vue.use(CarouselItem);
Vue.use(Pagination);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Select);
Vue.use(Option);
Vue.use(DatePicker);
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Switch)
Vue.use(Icon)
Vue.use(Upload)
Vue.use(Alert)
Vue.use(Radio)
Vue.use(RadioGroup)
//挂载 全局的 方法
Vue.prototype.$message = Message;
Vue.prototype.$confirm = MessageBox.confirm;
